version: "3"

services:
  nginx-react:
    container_name: bclcparks
    build:
        context: bclcparks/
    command: "nginx -g 'daemon off;'"
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - bclcparks
  bpp-app:
    build:
        context: backend
    env_file: ./backend/.env
    depends_on:
      - bpp-db
    environment:
        SQLALCHEMY_DATABASE_URI: "postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_USER}"
    ports:
      - 5000:5000
    volumes:
      - ./backend/app/:/app/
    restart: always
volumes:
  postgres-data:
networks:
  bclcparks:
    driver: bridge