version: "3"

services:
  nginx-react:
    container_name: bclcparks
    build:
        context: bclcparks/
    command: "nginx -g 'daemon off;'"
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - bclcparks
  app:
    build:
        context: backend
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file: ./backend/.env
    depends_on: 
      - db
    environment:
        SQLALCHEMY_DATABASE_URI: "postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_USER}"
    ports:
      - 5000:5000
    volumes:
      - ./backend/app/:/app/
    restart: always
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
volumes:
  postgres-data:
networks:
  bclcparks:
    driver: bridge