"""adding capacity type enum

Revision ID: 0ec17b648f68
Revises: a9fb1103c7a3
Create Date: 2021-05-14 17:38:40.080032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec17b648f68'
down_revision = 'a9fb1103c7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_type')
    op.drop_column('trailhead', 'capacity_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailhead', sa.Column('capacity_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('booking_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
