"""Trying an enum for state

Revision ID: 32ebe93bb91b
Revises: bd8fa260b710
Create Date: 2021-05-14 17:00:53.214056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ebe93bb91b'
down_revision = 'ab9562e911dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('state', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
