"""adding seed data

Revision ID: 4047e2141d5d
Revises: 7ca95323fa59
Create Date: 2021-05-13 21:32:14.908742

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4047e2141d5d'
down_revision = '7ca95323fa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailhead', sa.Column('capacity_type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trailhead', 'capacity_type')
    # ### end Alembic commands ###
