"""booking and trailhead

Revision ID: 7ca95323fa59
Revises: 0a7cf84acca9
Create Date: 2021-05-13 19:34:17.394985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca95323fa59'
down_revision = '0a7cf84acca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trailhead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_name', sa.String(length=80), nullable=False),
    sa.Column('trailhead_name', sa.String(length=80), nullable=False),
    sa.Column('am_capacity', sa.Integer(), nullable=False),
    sa.Column('pm_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_no', sa.String(length=15), nullable=True),
    sa.Column('passcode', sa.String(length=20), nullable=False),
    sa.Column('trailhead_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('am_or_pm', sa.Boolean(), nullable=False),
    sa.Column('booking_type', sa.String(), nullable=False),
    sa.Column('num_of_persons', sa.Integer(), nullable=True),
    sa.Column('vehicle_licence_plate', sa.String(length=12), nullable=True),
    sa.Column('application_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trailhead_id'], ['trailhead.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('trailhead')
    # ### end Alembic commands ###
