"""enum pt2

Revision ID: a9fb1103c7a3
Revises: 32ebe93bb91b
Create Date: 2021-05-14 17:20:51.201483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a9fb1103c7a3'
down_revision = '32ebe93bb91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bookingstate = postgresql.ENUM('WAITING', 'STANDBY', 'OPT-OUT', 'PASS OFFERED', 'BOOKING CONFIRMED', 'PASS CANCELED', name='bookingstate')
    bookingstate.create(op.get_bind())

    op.add_column('booking', sa.Column('state', sa.Enum('WAITING', 'STANDBY', 'OPT-OUT', 'PASS OFFERED', 'BOOKING CONFIRMED', 'PASS CANCELED', name='bookingstate'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'state')

    bookingstate = postgresql.ENUM('WAITING', 'STANDBY', 'OPT-OUT', 'PASS OFFERED', 'BOOKING CONFIRMED', 'PASS CANCELED', name='bookingstate')
    bookingstate.drop(op.get_bind())
    # ### end Alembic commands ###
