"""th_id non nullable

Revision ID: ab9562e911dc
Revises: bd8fa260b710
Create Date: 2021-05-14 16:42:40.467676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9562e911dc'
down_revision = 'bd8fa260b710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'trailhead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'trailhead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
